[package]
name = "Mandelblot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.0"
colors-transform = "0.2.11"
clap = "4.1.4"